In [6]:
# TÍTULO: Entrenamiento Comparativo - YOLOv8 vs Custom CNN (OCR)
# OBJETIVO: Entrenar y comparar dos arquitecturas para clasificación de caracteres.

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from ultralytics import YOLO
import os
import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report
from datetime import datetime
from tqdm.notebook import tqdm

# --- CONFIGURACIÓN DE HARDWARE ---
print(f"PyTorch Version: {torch.__version__}")
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
    print(f"GPU Activa: {torch.cuda.get_device_name(0)}")
else:
    DEVICE = torch.device('cpu')
    print("ALERTA: Usando CPU. El entrenamiento será lento.")

# --- RUTAS ---
# Dataset generado en el paso anterior
DATASET_DIR = '../../datasets/03_caracteres' 
# Carpeta para guardar ambos modelos
PROJECT_DIR = '../../models/03_caracteres'
os.makedirs(PROJECT_DIR, exist_ok=True)

# Parámetros Globales
IMG_SIZE = 64      # Tamaño de entrada (caracteres son pequeños)
BATCH_SIZE = 64
EPOCHS = 20        # Suficiente para caracteres simples
NUM_CLASSES = 36   # A-Z (26) + 0-9 (10) = 36 (Ajustar si tienes menos)

print("Entorno listo.")

PyTorch Version: 2.9.1+cu126
GPU Activa: NVIDIA GeForce RTX 4070 Ti
Entorno listo.

In [7]:
# Transformaciones para la CNN Custom (Normalización estándar)
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    # Normalización estándar para imágenes RGB
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Cargar Datasets usando ImageFolder (detecta carpetas A, B, C...)
train_dir = os.path.join(DATASET_DIR, 'train')
val_dir = os.path.join(DATASET_DIR, 'val')

# Verificación de seguridad
if not os.path.exists(train_dir):
    raise FileNotFoundError(f"No se encuentra el dataset en {train_dir}")

train_dataset = datasets.ImageFolder(train_dir, transform=transform)
val_dataset = datasets.ImageFolder(val_dir, transform=transform)

# Dataloaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Guardar nombres de clases
CLASS_NAMES = train_dataset.classes
NUM_CLASSES = len(CLASS_NAMES)

print(f"Datos cargados:")
print(f"   - Clases ({NUM_CLASSES}): {CLASS_NAMES[:5]}...")
print(f"   - Train images: {len(train_dataset)}")
print(f"   - Val images:   {len(val_dataset)}")

Datos cargados:
   - Clases (36): ['0', '1', '2', '3', '4']...
   - Train images: 168588
   - Val images:   42198

In [11]:
print("\ROUND 1: Entrenando YOLOv8 Nano (Classifier)...")

# Nombre del experimento YOLO
run_name_yolo = f"{datetime.now().strftime('%Y%m%d')}_ocr_yolo_v8n"

# Cargar modelo
model_yolo = YOLO('yolov8n-cls.pt')

# Entrenar
start_time = time.time()
results_yolo = model_yolo.train(
    data=DATASET_DIR,
    project=PROJECT_DIR,
    name=run_name_yolo,
    epochs=EPOCHS,
    imgsz=IMG_SIZE,
    batch=BATCH_SIZE,
    pretrained=True,
    device=0 if torch.cuda.is_available() else 'cpu',
    verbose=True
)
yolo_train_time = time.time() - start_time

print(f"YOLO entrenamiento completado en {yolo_train_time:.2f} segundos.")

\ROUND 1: Entrenando YOLOv8 Nano (Classifier)...
New https://pypi.org/project/ultralytics/8.3.234 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.233 🚀 Python-3.11.14 torch-2.9.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 11852MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=64, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=../../datasets/03_caracteres, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=64, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=20251202_ocr_yolo_v8n2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=../../models/03_caracteres, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/home/roberto/moca_proyecto/models/03_caracteres/20251202_ocr_yolo_v8n2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train... found 5504 images in 36 classes ✅
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val... found 1373 images in 36 classes ✅
test: None...
Overriding model.yaml nc=1000 with nc=36

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    376356  ultralytics.nn.modules.head.Classify         [256, 36]
YOLOv8n-cls summary: 56 layers, 1,484,404 parameters, 1,484,404 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 185.1±66.0 MB/s, size: 3.0 KB)
train: Scanning /home/roberto/moca_proyecto/datasets/03_caracteres/train... 5504 images, 0 corrupt: 100% ━━━━━━━━━━━━ 5504/5504 10.8Mit/s 0.0s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 70.7±27.7 MB/s, size: 1.8 KB)
val: Scanning /home/roberto/moca_proyecto/datasets/03_caracteres/val... 1373 images, 0 corrupt: 100% ━━━━━━━━━━━━ 1373/1373 2.6Mit/s 0.0ss
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00025, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
Image sizes 64 train, 64 val
Using 8 dataloader workers
Logging results to /home/roberto/moca_proyecto/models/03_caracteres/20251202_ocr_yolo_v8n2
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50     0.408G      3.716         64         64: 100% ━━━━━━━━━━━━ 86/86 50.9it/s 1.7s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 160.8it/s 0.1s
                   all      0.059      0.257

      Epoch    GPU_mem       loss  Instances       Size
       2/50     0.416G      3.286         64         64: 100% ━━━━━━━━━━━━ 86/86 62.1it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 168.6it/s 0.1s
                   all      0.185      0.499

      Epoch    GPU_mem       loss  Instances       Size
       3/50     0.416G      2.775         64         64: 100% ━━━━━━━━━━━━ 86/86 63.3it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 150.6it/s 0.1s
                   all      0.359      0.718

      Epoch    GPU_mem       loss  Instances       Size
       4/50     0.416G        2.3         64         64: 100% ━━━━━━━━━━━━ 86/86 61.8it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 180.9it/s 0.1s
                   all       0.49      0.834

      Epoch    GPU_mem       loss  Instances       Size
       5/50     0.416G      1.941         64         64: 100% ━━━━━━━━━━━━ 86/86 61.0it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 173.0it/s 0.1s
                   all      0.565      0.883

      Epoch    GPU_mem       loss  Instances       Size
       6/50     0.416G      1.729         64         64: 100% ━━━━━━━━━━━━ 86/86 61.2it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 178.8it/s 0.1s
                   all      0.626      0.894

      Epoch    GPU_mem       loss  Instances       Size
       7/50     0.416G      1.576         64         64: 100% ━━━━━━━━━━━━ 86/86 62.8it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 188.8it/s 0.1s
                   all      0.637      0.911

      Epoch    GPU_mem       loss  Instances       Size
       8/50     0.416G      1.453         64         64: 100% ━━━━━━━━━━━━ 86/86 64.5it/s 1.3s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 183.0it/s 0.1s
                   all      0.669      0.924

      Epoch    GPU_mem       loss  Instances       Size
       9/50     0.418G      1.396         64         64: 100% ━━━━━━━━━━━━ 86/86 62.3it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 179.8it/s 0.1s
                   all      0.688      0.929

      Epoch    GPU_mem       loss  Instances       Size
      10/50     0.426G      1.299         64         64: 100% ━━━━━━━━━━━━ 86/86 62.8it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 199.3it/s 0.1s
                   all      0.693      0.945

      Epoch    GPU_mem       loss  Instances       Size
      11/50     0.426G      1.222         64         64: 100% ━━━━━━━━━━━━ 86/86 63.2it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 159.2it/s 0.1s
                   all      0.715      0.942

      Epoch    GPU_mem       loss  Instances       Size
      12/50     0.426G      1.221         64         64: 100% ━━━━━━━━━━━━ 86/86 65.0it/s 1.3s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 170.8it/s 0.1s
                   all      0.727      0.948

      Epoch    GPU_mem       loss  Instances       Size
      13/50     0.426G      1.149         64         64: 100% ━━━━━━━━━━━━ 86/86 65.8it/s 1.3s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 169.6it/s 0.1s
                   all      0.728      0.949

      Epoch    GPU_mem       loss  Instances       Size
      14/50     0.426G      1.118         64         64: 100% ━━━━━━━━━━━━ 86/86 63.6it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 196.2it/s 0.1s
                   all      0.735      0.947

      Epoch    GPU_mem       loss  Instances       Size
      15/50     0.426G      1.097         64         64: 100% ━━━━━━━━━━━━ 86/86 62.7it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 135.2it/s 0.1s
                   all       0.75      0.953

      Epoch    GPU_mem       loss  Instances       Size
      16/50     0.426G      1.063         64         64: 100% ━━━━━━━━━━━━ 86/86 63.0it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 188.8it/s 0.1s
                   all      0.741      0.956

      Epoch    GPU_mem       loss  Instances       Size
      17/50     0.426G      1.043         64         64: 100% ━━━━━━━━━━━━ 86/86 65.6it/s 1.3s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 133.6it/s 0.1s
                   all      0.746      0.953

      Epoch    GPU_mem       loss  Instances       Size
      18/50     0.426G      1.006         64         64: 100% ━━━━━━━━━━━━ 86/86 62.7it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 183.6it/s 0.1s
                   all      0.755      0.956

      Epoch    GPU_mem       loss  Instances       Size
      19/50     0.426G     0.9978         64         64: 100% ━━━━━━━━━━━━ 86/86 58.8it/s 1.5s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 144.6it/s 0.1s
                   all      0.768       0.96

      Epoch    GPU_mem       loss  Instances       Size
      20/50     0.426G     0.9516         64         64: 100% ━━━━━━━━━━━━ 86/86 59.6it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 173.1it/s 0.1s
                   all      0.776      0.961

      Epoch    GPU_mem       loss  Instances       Size
      21/50     0.426G     0.9482         64         64: 100% ━━━━━━━━━━━━ 86/86 61.2it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 166.3it/s 0.1s
                   all      0.778      0.963

      Epoch    GPU_mem       loss  Instances       Size
      22/50     0.426G     0.8943         64         64: 100% ━━━━━━━━━━━━ 86/86 59.2it/s 1.5s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 197.7it/s 0.1s
                   all      0.779      0.964

      Epoch    GPU_mem       loss  Instances       Size
      23/50     0.426G     0.8994         64         64: 100% ━━━━━━━━━━━━ 86/86 60.0it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 184.8it/s 0.1s
                   all      0.781      0.962

      Epoch    GPU_mem       loss  Instances       Size
      24/50     0.426G     0.8839         64         64: 100% ━━━━━━━━━━━━ 86/86 60.1it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 169.7it/s 0.1s
                   all      0.779      0.962

      Epoch    GPU_mem       loss  Instances       Size
      25/50     0.426G     0.8619         64         64: 100% ━━━━━━━━━━━━ 86/86 60.3it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 208.9it/s 0.1s
                   all       0.79      0.961

      Epoch    GPU_mem       loss  Instances       Size
      26/50     0.426G     0.8443         64         64: 100% ━━━━━━━━━━━━ 86/86 58.3it/s 1.5s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 199.5it/s 0.1s
                   all      0.794      0.961

      Epoch    GPU_mem       loss  Instances       Size
      27/50     0.426G     0.8246         64         64: 100% ━━━━━━━━━━━━ 86/86 60.0it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 220.0it/s 0.0s
                   all      0.795      0.962

      Epoch    GPU_mem       loss  Instances       Size
      28/50     0.426G     0.8254         64         64: 100% ━━━━━━━━━━━━ 86/86 58.3it/s 1.5s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 208.2it/s 0.1s
                   all      0.795      0.961

      Epoch    GPU_mem       loss  Instances       Size
      29/50     0.426G     0.8279         64         64: 100% ━━━━━━━━━━━━ 86/86 60.7it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 168.1it/s 0.1s
                   all      0.794      0.959

      Epoch    GPU_mem       loss  Instances       Size
      30/50     0.426G     0.7949         64         64: 100% ━━━━━━━━━━━━ 86/86 61.7it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 195.7it/s 0.1s
                   all      0.805      0.962

      Epoch    GPU_mem       loss  Instances       Size
      31/50     0.426G     0.7781         64         64: 100% ━━━━━━━━━━━━ 86/86 62.0it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 195.6it/s 0.1s
                   all      0.801      0.962

      Epoch    GPU_mem       loss  Instances       Size
      32/50     0.426G     0.7804         64         64: 100% ━━━━━━━━━━━━ 86/86 59.5it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 202.7it/s 0.1s
                   all      0.817      0.961

      Epoch    GPU_mem       loss  Instances       Size
      33/50     0.426G     0.7852         64         64: 100% ━━━━━━━━━━━━ 86/86 58.8it/s 1.5s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 201.5it/s 0.1s
                   all      0.817      0.965

      Epoch    GPU_mem       loss  Instances       Size
      34/50     0.426G     0.7645         64         64: 100% ━━━━━━━━━━━━ 86/86 59.8it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 187.7it/s 0.1s
                   all      0.813      0.968

      Epoch    GPU_mem       loss  Instances       Size
      35/50     0.426G     0.7558         64         64: 100% ━━━━━━━━━━━━ 86/86 60.7it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 166.5it/s 0.1s
                   all      0.819      0.969

      Epoch    GPU_mem       loss  Instances       Size
      36/50     0.426G     0.7475         64         64: 100% ━━━━━━━━━━━━ 86/86 60.9it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 137.0it/s 0.1s
                   all      0.817      0.966

      Epoch    GPU_mem       loss  Instances       Size
      37/50     0.426G     0.7043         64         64: 100% ━━━━━━━━━━━━ 86/86 61.6it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 175.3it/s 0.1s
                   all      0.814      0.967

      Epoch    GPU_mem       loss  Instances       Size
      38/50     0.426G     0.7238         64         64: 100% ━━━━━━━━━━━━ 86/86 61.9it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 183.5it/s 0.1s
                   all      0.819      0.968

      Epoch    GPU_mem       loss  Instances       Size
      39/50     0.426G     0.7017         64         64: 100% ━━━━━━━━━━━━ 86/86 56.3it/s 1.5s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 173.0it/s 0.1s
                   all      0.811      0.969

      Epoch    GPU_mem       loss  Instances       Size
      40/50     0.426G     0.7304         64         64: 100% ━━━━━━━━━━━━ 86/86 60.8it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 135.1it/s 0.1s
                   all      0.818      0.969

      Epoch    GPU_mem       loss  Instances       Size
      41/50     0.426G     0.7313         64         64: 100% ━━━━━━━━━━━━ 86/86 59.4it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 184.6it/s 0.1s
                   all      0.816       0.97

      Epoch    GPU_mem       loss  Instances       Size
      42/50     0.426G     0.6993         64         64: 100% ━━━━━━━━━━━━ 86/86 62.3it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 185.7it/s 0.1s
                   all      0.814      0.971

      Epoch    GPU_mem       loss  Instances       Size
      43/50     0.426G     0.7035         64         64: 100% ━━━━━━━━━━━━ 86/86 61.0it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 182.9it/s 0.1s
                   all      0.816      0.971

      Epoch    GPU_mem       loss  Instances       Size
      44/50     0.426G     0.6997         64         64: 100% ━━━━━━━━━━━━ 86/86 62.1it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 150.8it/s 0.1s
                   all      0.811      0.969

      Epoch    GPU_mem       loss  Instances       Size
      45/50     0.426G     0.6935         64         64: 100% ━━━━━━━━━━━━ 86/86 61.5it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 204.5it/s 0.1s
                   all      0.818      0.967

      Epoch    GPU_mem       loss  Instances       Size
      46/50     0.426G     0.6896         64         64: 100% ━━━━━━━━━━━━ 86/86 64.2it/s 1.3s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 129.4it/s 0.1s
                   all      0.818      0.967

      Epoch    GPU_mem       loss  Instances       Size
      47/50     0.426G     0.6863         64         64: 100% ━━━━━━━━━━━━ 86/86 64.3it/s 1.3s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 180.6it/s 0.1s
                   all      0.817      0.967

      Epoch    GPU_mem       loss  Instances       Size
      48/50     0.426G     0.6607         64         64: 100% ━━━━━━━━━━━━ 86/86 63.5it/s 1.4s0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 203.7it/s 0.1s
                   all      0.817      0.967

      Epoch    GPU_mem       loss  Instances       Size
      49/50     0.426G     0.6796         64         64: 100% ━━━━━━━━━━━━ 86/86 63.1it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 180.7it/s 0.1s
                   all      0.822      0.969

      Epoch    GPU_mem       loss  Instances       Size
      50/50     0.426G     0.6824         64         64: 100% ━━━━━━━━━━━━ 86/86 63.6it/s 1.4s0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 134.8it/s 0.1s
                   all      0.824       0.97

50 epochs completed in 0.022 hours.
Optimizer stripped from /home/roberto/moca_proyecto/models/03_caracteres/20251202_ocr_yolo_v8n2/weights/last.pt, 3.1MB
Optimizer stripped from /home/roberto/moca_proyecto/models/03_caracteres/20251202_ocr_yolo_v8n2/weights/best.pt, 3.1MB

Validating /home/roberto/moca_proyecto/models/03_caracteres/20251202_ocr_yolo_v8n2/weights/best.pt...
Ultralytics 8.3.233 🚀 Python-3.11.14 torch-2.9.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 11852MiB)
YOLOv8n-cls summary (fused): 30 layers, 1,480,996 parameters, 0 gradients, 3.3 GFLOPs
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train... found 5504 images in 36 classes ✅
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val... found 1373 images in 36 classes ✅
test: None...
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 11/11 177.8it/s 0.1s
                   all      0.823       0.97
Speed: 0.0ms preprocess, 0.0ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /home/roberto/moca_proyecto/models/03_caracteres/20251202_ocr_yolo_v8n2
YOLO entrenamiento completado en 81.17 segundos.

In [12]:
class CustomOCR_CNN(nn.Module):
    def __init__(self, num_classes):
        super(CustomOCR_CNN, self).__init__()
        
        # Bloque Convolucional 1
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Salida: 32x32
        )
        
        # Bloque Convolucional 2
        self.conv2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Salida: 16x16
        )
        
        # Bloque Convolucional 3
        self.conv3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Salida: 8x8
        )
        
        # Clasificador (Fully Connected)
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 8 * 8, 512), # Ajustar según IMG_SIZE (64 -> 8x8 feature map)
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.fc(x)
        return x

print("Arquitectura CNN definida.")

Arquitectura CNN definida.

In [13]:
print("\nROUND 2: Entrenando CNN Personalizada...")

# Instanciar modelo
cnn_model = CustomOCR_CNN(num_classes=NUM_CLASSES).to(DEVICE)

# Configuración
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn_model.parameters(), lr=0.001)

# Historial
cnn_history = {'loss': [], 'acc': []}

start_time = time.time()

for epoch in range(EPOCHS):
    cnn_model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    
    # Barra de progreso
    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)
    
    for inputs, labels in pbar:
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
        
        optimizer.zero_grad()
        
        # Forward
        outputs = cnn_model(inputs)
        loss = criterion(outputs, labels)
        
        # Backward
        loss.backward()
        optimizer.step()
        
        # Métricas
        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()
        
        pbar.set_postfix({'loss': f'{loss.item():.4f}'})
    
    epoch_loss = running_loss / len(train_loader)
    epoch_acc = correct / total
    cnn_history['loss'].append(epoch_loss)
    cnn_history['acc'].append(epoch_acc)
    
    print(f"   Epoch {epoch+1}: Loss={epoch_loss:.4f}, Accuracy={epoch_acc:.4f}")

cnn_train_time = time.time() - start_time
print(f"CNN Entrenamiento completado en {cnn_train_time:.2f} segundos.")

# Guardar modelo CNN
cnn_save_path = os.path.join(PROJECT_DIR, 'custom_cnn_best.pth')
torch.save(cnn_model.state_dict(), cnn_save_path)
print(f"Modelo guardado en: {cnn_save_path}")

ROUND 2: Entrenando CNN Personalizada...

Epoch 1/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 1: Loss=3.7714, Accuracy=0.0505

Epoch 2/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 2: Loss=3.4054, Accuracy=0.0747

Epoch 3/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 3: Loss=3.1855, Accuracy=0.1201

Epoch 4/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 4: Loss=2.8651, Accuracy=0.1759

Epoch 5/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 5: Loss=2.6276, Accuracy=0.2318

Epoch 6/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 6: Loss=2.4410, Accuracy=0.2760

Epoch 7/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 7: Loss=2.3214, Accuracy=0.2842

Epoch 8/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 8: Loss=2.2146, Accuracy=0.3060

Epoch 9/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 9: Loss=2.1695, Accuracy=0.3178

Epoch 10/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 10: Loss=2.1217, Accuracy=0.3276

Epoch 11/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 11: Loss=2.0699, Accuracy=0.3230

Epoch 12/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 12: Loss=2.0236, Accuracy=0.3516

Epoch 13/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 13: Loss=2.0253, Accuracy=0.3414

Epoch 14/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 14: Loss=1.9701, Accuracy=0.3570

Epoch 15/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 15: Loss=1.9610, Accuracy=0.3585

Epoch 16/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 16: Loss=1.9399, Accuracy=0.3616

Epoch 17/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 17: Loss=1.8891, Accuracy=0.3812

Epoch 18/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 18: Loss=1.8979, Accuracy=0.3610

Epoch 19/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 19: Loss=1.8724, Accuracy=0.3739

Epoch 20/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 20: Loss=1.8353, Accuracy=0.3955

Epoch 21/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 21: Loss=1.8656, Accuracy=0.3775

Epoch 22/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 22: Loss=1.8247, Accuracy=0.3872

Epoch 23/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 23: Loss=1.8147, Accuracy=0.3884

Epoch 24/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 24: Loss=1.8066, Accuracy=0.3941

Epoch 25/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 25: Loss=1.7726, Accuracy=0.4073

Epoch 26/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 26: Loss=1.7505, Accuracy=0.4130

Epoch 27/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 27: Loss=1.7217, Accuracy=0.4046

Epoch 28/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 28: Loss=1.7590, Accuracy=0.4141

Epoch 29/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 29: Loss=1.7399, Accuracy=0.4066

Epoch 30/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 30: Loss=1.7384, Accuracy=0.4102

Epoch 31/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 31: Loss=1.7249, Accuracy=0.4186

Epoch 32/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 32: Loss=1.6864, Accuracy=0.4221

Epoch 33/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 33: Loss=1.6563, Accuracy=0.4199

Epoch 34/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 34: Loss=1.6831, Accuracy=0.4208

Epoch 35/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 35: Loss=1.6462, Accuracy=0.4346

Epoch 36/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 36: Loss=1.6630, Accuracy=0.4253

Epoch 37/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 37: Loss=1.6754, Accuracy=0.4206

Epoch 38/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 38: Loss=1.6505, Accuracy=0.4261

Epoch 39/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 39: Loss=1.6394, Accuracy=0.4306

Epoch 40/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 40: Loss=1.6000, Accuracy=0.4446

Epoch 41/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 41: Loss=1.6468, Accuracy=0.4410

Epoch 42/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 42: Loss=1.6111, Accuracy=0.4408

Epoch 43/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 43: Loss=1.6015, Accuracy=0.4477

Epoch 44/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 44: Loss=1.6186, Accuracy=0.4397

Epoch 45/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 45: Loss=1.6012, Accuracy=0.4411

Epoch 46/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 46: Loss=1.5923, Accuracy=0.4477

Epoch 47/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 47: Loss=1.6049, Accuracy=0.4457

Epoch 48/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 48: Loss=1.5777, Accuracy=0.4460

Epoch 49/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 49: Loss=1.5892, Accuracy=0.4475

Epoch 50/50:   0%|          | 0/86 [00:00<?, ?it/s]

   Epoch 50: Loss=1.5660, Accuracy=0.4588
CNN Entrenamiento completado en 89.90 segundos.
Modelo guardado en: ../../models/03_caracteres/custom_cnn_best.pth

In [8]:
def evaluate_model(model, loader, model_type='cnn'):
    model.eval() # Modo evaluación (importante para Dropout/BatchNorm)
    all_preds = []
    all_labels = []
    inference_times = []
    
    print(f"Evaluando {model_type}...")
    
    with torch.no_grad():
        for inputs, labels in tqdm(loader):
            # Preparar inputs según modelo
            if model_type == 'cnn':
                inputs = inputs.to(DEVICE)
            else:
                # YOLO espera rutas de archivos o arrays numpy, pero aquí
                # estamos pasando tensores. Para ser justos en velocidad,
                # usaremos el método .predict() de YOLO en lote si es posible,
                # o convertiremos. Para simplificar, usaremos validación integrada de YOLO arriba
                # y aquí solo mediremos CNN, luego uniremos datos.
                pass 

            if model_type == 'cnn':
                start = time.time()
                outputs = model(inputs)
                end = time.time()
                
                _, predicted = outputs.max(1)
                all_preds.extend(predicted.cpu().numpy())
                all_labels.extend(labels.numpy())
                
                # Tiempo por batch -> Tiempo por imagen
                inference_times.append((end - start) / inputs.size(0))

    if model_type == 'cnn':
        acc = accuracy_score(all_labels, all_preds)
        avg_inference_ms = (sum(inference_times) / len(inference_times)) * 1000
        return acc, avg_inference_ms

# 1. Evaluar CNN
cnn_acc, cnn_speed = evaluate_model(cnn_model, val_loader, 'cnn')

# 2. Obtener métricas de YOLO (del objeto results)
# YOLO calcula esto automáticamente al entrenar
yolo_metrics = model_yolo.val()
yolo_acc = yolo_metrics.top1
yolo_speed = yolo_metrics.speed['inference'] # ms per image

# --- REPORTE FINAL ---
comparison_data = {
    'Modelo': ['YOLOv8n-CLS', 'Custom CNN'],
    'Accuracy (Top-1)': [yolo_acc, cnn_acc],
    'Tiempo Entrenamiento (s)': [yolo_train_time, cnn_train_time],
    'Velocidad Inferencia (ms/img)': [yolo_speed, cnn_speed]
}

df_results = pd.DataFrame(comparison_data)

print("\n🏆 TABLA DE RESULTADOS:")
display(df_results)

# Graficar
fig, ax = plt.subplots(1, 3, figsize=(18, 5))

# Gráfica 1: Accuracy
sns.barplot(data=df_results, x='Modelo', y='Accuracy (Top-1)', ax=ax[0], palette='viridis')
ax[0].set_title('Precisión (Más alto es mejor)')
ax[0].set_ylim(0, 1.1)
for i, v in enumerate(df_results['Accuracy (Top-1)']):
    ax[0].text(i, v + 0.02, f"{v:.2%}", ha='center')

# Gráfica 2: Velocidad
sns.barplot(data=df_results, x='Modelo', y='Velocidad Inferencia (ms/img)', ax=ax[1], palette='rocket')
ax[1].set_title('Latencia (Más bajo es mejor)')
for i, v in enumerate(df_results['Velocidad Inferencia (ms/img)']):
    ax[1].text(i, v + 0.1, f"{v:.2f} ms", ha='center')

# Gráfica 3: Tiempo Entrenamiento
sns.barplot(data=df_results, x='Modelo', y='Tiempo Entrenamiento (s)', ax=ax[2], palette='magma')
ax[2].set_title('Costo de Entrenamiento (Segundos)')

plt.tight_layout()
plt.show()

Evaluando cnn...

  0%|          | 0/22 [00:00<?, ?it/s]

Ultralytics 8.3.233 🚀 Python-3.11.14 torch-2.9.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 11852MiB)
YOLOv8n-cls summary (fused): 30 layers, 1,480,996 parameters, 0 gradients, 3.3 GFLOPs
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train... found 5504 images in 36 classes ✅
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val... found 1373 images in 36 classes ✅
test: None...
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 138.9±42.7 MB/s, size: 1.8 KB)
val: Scanning /home/roberto/moca_proyecto/datasets/03_caracteres/val... 1373 images, 0 corrupt: 100% ━━━━━━━━━━━━ 1373/1373 4.8Mit/s 0.0s0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 86/86 300.6it/s 0.3s0.2s
                   all        0.7      0.943
Speed: 0.0ms preprocess, 0.2ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /home/roberto/moca_proyecto/notebooks/03_caracteres/runs/classify/val3

🏆 TABLA DE RESULTADOS:

,Modelo,Accuracy (Top-1),Tiempo Entrenamiento (s),Velocidad Inferencia (ms/img)
0,YOLOv8n-CLS,0.699927,31.136698,0.180391
1,Custom CNN,0.612527,27.832779,0.015901

/tmp/ipykernel_4787/1340333088.py:65: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df_results, x='Modelo', y='Accuracy (Top-1)', ax=ax[0], palette='viridis')
/tmp/ipykernel_4787/1340333088.py:72: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df_results, x='Modelo', y='Velocidad Inferencia (ms/img)', ax=ax[1], palette='rocket')
/tmp/ipykernel_4787/1340333088.py:78: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df_results, x='Modelo', y='Tiempo Entrenamiento (s)', ax=ax[2], palette='magma')

In [8]:
print("\ROUND 1: Entrenando YOLOv8 Nano (Classifier) para 30,000 imágenes...")

# Nombre del experimento YOLO
run_name_yolo = f"{datetime.now().strftime('%Y%m%d')}_ocr_yolo_v8n_30k"

# Cargar modelo
model_yolo = YOLO('yolov8n-cls.pt')

# Entrenar
start_time = time.time()
results_yolo = model_yolo.train(
    data=DATASET_DIR,
    project=PROJECT_DIR,
    name=run_name_yolo,
    epochs=EPOCHS,
    imgsz=IMG_SIZE,
    batch=BATCH_SIZE,
    pretrained=True,
    device=0 if torch.cuda.is_available() else 'cpu',
    verbose=True
)
yolo_train_time = time.time() - start_time

print(f"YOLO entrenamiento completado en {yolo_train_time:.2f} segundos.")

\ROUND 1: Entrenando YOLOv8 Nano (Classifier) para 30,000 imágenes...
New https://pypi.org/project/ultralytics/8.3.234 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.233 🚀 Python-3.11.14 torch-2.9.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 11852MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=64, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=../../datasets/03_caracteres, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=20, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=64, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=20251203_ocr_yolo_v8n_30k2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=../../models/03_caracteres, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/home/roberto/moca_proyecto/models/03_caracteres/20251203_ocr_yolo_v8n_30k2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train... found 168588 images in 36 classes ✅
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val... found 42198 images in 36 classes ✅
test: None...
Overriding model.yaml nc=1000 with nc=36

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    376356  ultralytics.nn.modules.head.Classify         [256, 36]
YOLOv8n-cls summary: 56 layers, 1,484,404 parameters, 1,484,404 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 228.8±115.2 MB/s, size: 2.8 KB)
train: Scanning /home/roberto/moca_proyecto/datasets/03_caracteres/train... 168577 images, 11 corrupt: 100% ━━━━━━━━━━━━ 168577/168577 336.5Mit/s 0.0s
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/1/KGA-35-13_3035_5.jpg: ignoring corrupt image/label: image size (28, 9) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/1/MTC-13-39_3768_3.jpg: ignoring corrupt image/label: image size (24, 9) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/F-547-WIS_6213_5.jpg: ignoring corrupt image/label: image size (25, 9) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/I-706-QVN_8390_0.jpg: ignoring corrupt image/label: image size (27, 9) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/K-863-IDR_2479_4.jpg: ignoring corrupt image/label: image size (25, 8) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/M-301-SRI_9494_6.jpg: ignoring corrupt image/label: image size (29, 9) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/M-385-IYP_3345_4.jpg: ignoring corrupt image/label: image size (30, 8) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/OLSIMVF_1589_3.jpg: ignoring corrupt image/label: image size (24, 8) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/PIR-74-46_5228_1.jpg: ignoring corrupt image/label: image size (29, 8) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/V-018-JIW_4765_5.jpg: ignoring corrupt image/label: image size (19, 7) <10 pixels
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train/I/XRRTTIF_6685_5.jpg: ignoring corrupt image/label: image size (26, 9) <10 pixels
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 128.5±58.1 MB/s, size: 3.7 KB)
val: Scanning /home/roberto/moca_proyecto/datasets/03_caracteres/val... 42197 images, 1 corrupt: 100% ━━━━━━━━━━━━ 42197/42197 99.9Mit/s 0.0s
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val/1/R-418-KOQ_6087_2.jpg: ignoring corrupt image/label: image size (19, 9) <10 pixels
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
Image sizes 64 train, 64 val
Using 8 dataloader workers
Logging results to /home/roberto/moca_proyecto/models/03_caracteres/20251203_ocr_yolo_v8n_30k2
Starting training for 20 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/20     0.271G      2.318          1         64: 100% ━━━━━━━━━━━━ 2635/2635 59.8it/s 44.1s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 145.1it/s 2.3s0.1s
                   all      0.726       0.95

      Epoch    GPU_mem       loss  Instances       Size
       2/20     0.271G        1.1          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.3it/s 43.0s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 149.0it/s 2.2s0.0s
                   all      0.857      0.979

      Epoch    GPU_mem       loss  Instances       Size
       3/20     0.271G      0.869          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.6it/s 42.8s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 147.7it/s 2.2s0.1s
                   all      0.887      0.984

      Epoch    GPU_mem       loss  Instances       Size
       4/20     0.271G     0.7652          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.0it/s 43.2s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 146.1it/s 2.3s0.1s
                   all      0.916      0.989

      Epoch    GPU_mem       loss  Instances       Size
       5/20     0.271G     0.6771          1         64: 100% ━━━━━━━━━━━━ 2635/2635 60.4it/s 43.6s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 146.8it/s 2.2s0.1s
                   all      0.927       0.99

      Epoch    GPU_mem       loss  Instances       Size
       6/20     0.271G     0.6248          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.6it/s 42.8s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 146.5it/s 2.3s0.1s
                   all      0.931      0.991

      Epoch    GPU_mem       loss  Instances       Size
       7/20     0.271G     0.5992          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.7it/s 42.7s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 147.9it/s 2.2s0.1s
                   all      0.934      0.991

      Epoch    GPU_mem       loss  Instances       Size
       8/20     0.271G     0.5787          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.3it/s 43.0s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 145.8it/s 2.3s0.1s
                   all      0.936      0.992

      Epoch    GPU_mem       loss  Instances       Size
       9/20     0.271G     0.5589          1         64: 100% ━━━━━━━━━━━━ 2635/2635 60.9it/s 43.3s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 127.8it/s 2.6s0.1s
                   all      0.937      0.992

      Epoch    GPU_mem       loss  Instances       Size
      10/20     0.271G     0.5387          1         64: 100% ━━━━━━━━━━━━ 2635/2635 57.9it/s 45.5s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 144.9it/s 2.3s0.1s
                   all      0.938      0.992

      Epoch    GPU_mem       loss  Instances       Size
      11/20     0.271G     0.5203          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.4it/s 42.9s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 145.2it/s 2.3s0.1s
                   all      0.939      0.992

      Epoch    GPU_mem       loss  Instances       Size
      12/20     0.271G     0.5016          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.8it/s 42.6s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 147.2it/s 2.2s0.1s
                   all       0.94      0.993

      Epoch    GPU_mem       loss  Instances       Size
      13/20     0.271G     0.4821          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.7it/s 42.7s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 149.0it/s 2.2s0.1s
                   all       0.94      0.993

      Epoch    GPU_mem       loss  Instances       Size
      14/20     0.271G     0.4623          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.4it/s 42.9s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 146.1it/s 2.3s0.1s
                   all      0.941      0.993

      Epoch    GPU_mem       loss  Instances       Size
      15/20     0.271G     0.4431          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.8it/s 42.6s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 147.8it/s 2.2s0.1s
                   all      0.942      0.993

      Epoch    GPU_mem       loss  Instances       Size
      16/20     0.271G     0.4191          1         64: 100% ━━━━━━━━━━━━ 2635/2635 62.3it/s 42.3s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 149.5it/s 2.2s0.1s
                   all      0.943      0.993

      Epoch    GPU_mem       loss  Instances       Size
      17/20     0.271G     0.3968          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.6it/s 42.8s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 140.7it/s 2.3s0.1s
                   all      0.944      0.993

      Epoch    GPU_mem       loss  Instances       Size
      18/20     0.271G     0.3739          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.6it/s 42.8s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 145.8it/s 2.3s0.1s
                   all      0.946      0.994

      Epoch    GPU_mem       loss  Instances       Size
      19/20     0.271G      0.352          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.8it/s 42.7s<0.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 146.3it/s 2.3s0.1s
                   all      0.948      0.994

      Epoch    GPU_mem       loss  Instances       Size
      20/20     0.271G     0.3261          1         64: 100% ━━━━━━━━━━━━ 2635/2635 61.6it/s 42.7s<0.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 143.0it/s 2.3s0.0s
                   all       0.95      0.994

20 epochs completed in 0.253 hours.
Optimizer stripped from /home/roberto/moca_proyecto/models/03_caracteres/20251203_ocr_yolo_v8n_30k2/weights/last.pt, 3.1MB
Optimizer stripped from /home/roberto/moca_proyecto/models/03_caracteres/20251203_ocr_yolo_v8n_30k2/weights/best.pt, 3.1MB

Validating /home/roberto/moca_proyecto/models/03_caracteres/20251203_ocr_yolo_v8n_30k2/weights/best.pt...
Ultralytics 8.3.233 🚀 Python-3.11.14 torch-2.9.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 11852MiB)
YOLOv8n-cls summary (fused): 30 layers, 1,480,996 parameters, 0 gradients, 3.3 GFLOPs
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train... found 168588 images in 36 classes ✅
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val... found 42198 images in 36 classes ✅
test: None...
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 330/330 155.1it/s 2.1s0.1s
                   all       0.95      0.994
Speed: 0.0ms preprocess, 0.0ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /home/roberto/moca_proyecto/models/03_caracteres/20251203_ocr_yolo_v8n_30k2
YOLO entrenamiento completado en 921.48 segundos.

In [9]:
class CustomOCR_CNN(nn.Module):
    def __init__(self, num_classes):
        super(CustomOCR_CNN, self).__init__()
        
        # Bloque Convolucional 1
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Salida: 32x32
        )
        
        # Bloque Convolucional 2
        self.conv2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Salida: 16x16
        )
        
        # Bloque Convolucional 3
        self.conv3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Salida: 8x8
        )
        
        # Clasificador (Fully Connected)
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 8 * 8, 512), # Ajustar según IMG_SIZE (64 -> 8x8 feature map)
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.fc(x)
        return x

print("Arquitectura CNN definida.")

Arquitectura CNN definida.

In [10]:
print("\nROUND 2: Entrenando CNN Personalizada...")

# Instanciar modelo
cnn_model = CustomOCR_CNN(num_classes=NUM_CLASSES).to(DEVICE)

# Configuración
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn_model.parameters(), lr=0.001)

# Historial
cnn_history = {'loss': [], 'acc': []}

start_time = time.time()

for epoch in range(EPOCHS):
    cnn_model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    
    # Barra de progreso
    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)
    
    for inputs, labels in pbar:
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
        
        optimizer.zero_grad()
        
        # Forward
        outputs = cnn_model(inputs)
        loss = criterion(outputs, labels)
        
        # Backward
        loss.backward()
        optimizer.step()
        
        # Métricas
        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()
        
        pbar.set_postfix({'loss': f'{loss.item():.4f}'})
    
    epoch_loss = running_loss / len(train_loader)
    epoch_acc = correct / total
    cnn_history['loss'].append(epoch_loss)
    cnn_history['acc'].append(epoch_acc)
    
    print(f"   Epoch {epoch+1}: Loss={epoch_loss:.4f}, Accuracy={epoch_acc:.4f}")

cnn_train_time = time.time() - start_time
print(f"CNN Entrenamiento completado en {cnn_train_time:.2f} segundos.")

# Guardar modelo CNN
cnn_save_path = os.path.join(PROJECT_DIR, 'custom_cnn_best.pth')
torch.save(cnn_model.state_dict(), cnn_save_path)
print(f"Modelo guardado en: {cnn_save_path}")

ROUND 2: Entrenando CNN Personalizada...

Epoch 1/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 1: Loss=2.5670, Accuracy=0.2187

Epoch 2/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 2: Loss=2.2446, Accuracy=0.2844

Epoch 3/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 3: Loss=2.1693, Accuracy=0.3027

Epoch 4/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 4: Loss=2.1271, Accuracy=0.3119

Epoch 5/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 5: Loss=2.0232, Accuracy=0.3468

Epoch 6/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 6: Loss=1.9332, Accuracy=0.3744

Epoch 7/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 7: Loss=1.9083, Accuracy=0.3797

Epoch 8/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 8: Loss=1.8344, Accuracy=0.4023

Epoch 9/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 9: Loss=1.7382, Accuracy=0.4277

Epoch 10/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 10: Loss=1.6159, Accuracy=0.4588

Epoch 11/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 11: Loss=1.4967, Accuracy=0.4936

Epoch 12/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 12: Loss=1.4052, Accuracy=0.5226

Epoch 13/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 13: Loss=1.1706, Accuracy=0.5999

Epoch 14/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 14: Loss=0.9707, Accuracy=0.6669

Epoch 15/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 15: Loss=0.9329, Accuracy=0.6803

Epoch 16/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 16: Loss=0.8461, Accuracy=0.7102

Epoch 17/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 17: Loss=0.6967, Accuracy=0.7613

Epoch 18/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 18: Loss=0.5979, Accuracy=0.7959

Epoch 19/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 19: Loss=0.5694, Accuracy=0.8055

Epoch 20/20:   0%|          | 0/2635 [00:00<?, ?it/s]

   Epoch 20: Loss=0.5484, Accuracy=0.8130
CNN Entrenamiento completado en 1159.69 segundos.
Modelo guardado en: ../../models/03_caracteres/custom_cnn_best.pth

In [11]:
def evaluate_model(model, loader, model_type='cnn'):
    model.eval() # Modo evaluación (importante para Dropout/BatchNorm)
    all_preds = []
    all_labels = []
    inference_times = []
    
    print(f"Evaluando {model_type}...")
    
    with torch.no_grad():
        for inputs, labels in tqdm(loader):
            # Preparar inputs según modelo
            if model_type == 'cnn':
                inputs = inputs.to(DEVICE)
            else:
                # YOLO espera rutas de archivos o arrays numpy, pero aquí
                # estamos pasando tensores. Para ser justos en velocidad,
                # usaremos el método .predict() de YOLO en lote si es posible,
                # o convertiremos. Para simplificar, usaremos validación integrada de YOLO arriba
                # y aquí solo mediremos CNN, luego uniremos datos.
                pass 

            if model_type == 'cnn':
                start = time.time()
                outputs = model(inputs)
                end = time.time()
                
                _, predicted = outputs.max(1)
                all_preds.extend(predicted.cpu().numpy())
                all_labels.extend(labels.numpy())
                
                # Tiempo por batch -> Tiempo por imagen
                inference_times.append((end - start) / inputs.size(0))

    if model_type == 'cnn':
        acc = accuracy_score(all_labels, all_preds)
        avg_inference_ms = (sum(inference_times) / len(inference_times)) * 1000
        return acc, avg_inference_ms

# 1. Evaluar CNN
cnn_acc, cnn_speed = evaluate_model(cnn_model, val_loader, 'cnn')

# 2. Obtener métricas de YOLO (del objeto results)
# YOLO calcula esto automáticamente al entrenar
yolo_metrics = model_yolo.val()
yolo_acc = yolo_metrics.top1
yolo_speed = yolo_metrics.speed['inference'] # ms per image

# --- REPORTE FINAL ---
comparison_data = {
    'Modelo': ['YOLOv8n-CLS', 'Custom CNN'],
    'Accuracy (Top-1)': [yolo_acc, cnn_acc],
    'Tiempo Entrenamiento (s)': [yolo_train_time, cnn_train_time],
    'Velocidad Inferencia (ms/img)': [yolo_speed, cnn_speed]
}

df_results = pd.DataFrame(comparison_data)

print("\nTABLA DE RESULTADOS:")
display(df_results)

# Graficar
fig, ax = plt.subplots(1, 3, figsize=(18, 5))

# Gráfica 1: Accuracy
sns.barplot(data=df_results, x='Modelo', y='Accuracy (Top-1)', ax=ax[0], palette='viridis')
ax[0].set_title('Precisión (Más alto es mejor)')
ax[0].set_ylim(0, 1.1)
for i, v in enumerate(df_results['Accuracy (Top-1)']):
    ax[0].text(i, v + 0.02, f"{v:.2%}", ha='center')

# Gráfica 2: Velocidad
sns.barplot(data=df_results, x='Modelo', y='Velocidad Inferencia (ms/img)', ax=ax[1], palette='rocket')
ax[1].set_title('Latencia (Más bajo es mejor)')
for i, v in enumerate(df_results['Velocidad Inferencia (ms/img)']):
    ax[1].text(i, v + 0.1, f"{v:.2f} ms", ha='center')

# Gráfica 3: Tiempo Entrenamiento
sns.barplot(data=df_results, x='Modelo', y='Tiempo Entrenamiento (s)', ax=ax[2], palette='magma')
ax[2].set_title('Costo de Entrenamiento (Segundos)')

plt.tight_layout()
plt.show()

Evaluando cnn...

  0%|          | 0/660 [00:00<?, ?it/s]

Ultralytics 8.3.233 🚀 Python-3.11.14 torch-2.9.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 11852MiB)
YOLOv8n-cls summary (fused): 30 layers, 1,480,996 parameters, 0 gradients, 3.3 GFLOPs
train: /home/roberto/moca_proyecto/datasets/03_caracteres/train... found 168588 images in 36 classes ✅
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val... found 42198 images in 36 classes ✅
test: None...
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 294.5±126.7 MB/s, size: 3.7 KB)
val: Scanning /home/roberto/moca_proyecto/datasets/03_caracteres/val... 42197 images, 1 corrupt: 100% ━━━━━━━━━━━━ 42197/42197 108.0Mit/s 0.0s
val: /home/roberto/moca_proyecto/datasets/03_caracteres/val/1/R-418-KOQ_6087_2.jpg: ignoring corrupt image/label: image size (19, 9) <10 pixels
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 2638/2638 399.0it/s 6.6s<0.0s
                   all       0.95      0.994
Speed: 0.0ms preprocess, 0.1ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /home/roberto/moca_proyecto/notebooks/03_caracteres/runs/classify/val4

TABLA DE RESULTADOS:

,Modelo,Accuracy (Top-1),Tiempo Entrenamiento (s),Velocidad Inferencia (ms/img)
0,YOLOv8n-CLS,0.949949,921.477282,0.132728
1,Custom CNN,0.930755,1159.685794,0.007900

/tmp/ipykernel_9559/2504788383.py:65: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df_results, x='Modelo', y='Accuracy (Top-1)', ax=ax[0], palette='viridis')
/tmp/ipykernel_9559/2504788383.py:72: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df_results, x='Modelo', y='Velocidad Inferencia (ms/img)', ax=ax[1], palette='rocket')
/tmp/ipykernel_9559/2504788383.py:78: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df_results, x='Modelo', y='Tiempo Entrenamiento (s)', ax=ax[2], palette='magma')